dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-08/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: WaYsKUs8DlrdlFVUfBoZ+Ak4nC531tgb0lZQtqeS3HiUHT443YPdkfwYTGywKtTARv5owtgaiDCmqRichzR6dZPyknQsp4aHTUR+CP6gHf0PtIoM/8dAjwOJ8lZAMJrUs7twpIBnPgT1i1LWNqAxCfJXePECE5+GF+pJQ/j30MaBvlwqTA/+jE7gQth6BLJCsYe26GaL5+VQ+PZHbXbPYA9M4sjIJ7P32gfN1fmV+CHV4WDjDOtwRCWE+6RkDEMTeM/Ni3qu/g9tUur5CFKLTd1HL3HkLKJcBivnSnJzJFIaewp1sbs5rACLmu3byWxyiOZS6IHIDl97VzbHIjJb1e7VB8HeGksf0/lnosa2fJ21328jKBaah4xjIraM/ajz7xNM5nNyxJHDev2PcD9GQN7xGbxJNYkqvrpsuPY6qVXkl4MPozzcYMQTnT8/rMr2VwpqUC0dadEP6zLniO8V8Q+//pRfF+9XUFP5dobqBISUOlplDcf7VwfjLb0NycvsTIgQJWUyYCEm9QExr0Q/nrToNiJN1LmCIiiwLEMyA/njA7RoxNOHrKNxQnwK0LxpJFKFtQFLiNDVSpDwXbpQ9exgOxMy7TsQvQSMHzLuwlX+/O4y+ZKl8Z+t6kwwA0nEtW0eDKOUrs2FZJ+PKtM4+oTNC8DYfjkKIbPWVr13AhA=
