dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-08/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: 0ldSKuSEKGvkdFKYhINGhDv4OPgqQ9+xHWv5mcBtrehk/UDkGt/dUfZT0OFpNEyG7Kd7DvI9UCyPz2/GdsxUU3KjJUD46ODT5+UNEK+qxctr3oHlOOnQb/2rdxzOOHvr3B2OOGsj5+GGsHGgYbOvq4nwUgGmU2T3M/xykw/bI85wfQ4nWT34Ud/ul1vUb43aJlUykkL5zOZ2Q6ybHh5MX6zQvnACIZMtFYSPvutphwpDJpQLx51Hwo9dJKHt2JjxUoZi5xCl+ELpS3j/0D6lKD+cUUD9cxk5c9kU8ol2NAfYwa7iUaG6czfI+h+J0aDzFd2uEHmrMVyY1cQL4JCkMXllaFd8NgP6HidDPyq52hDUlFmrnsDPXNnDMydeJ2SD8gbKA0knQOeTzaQGNT0d9wZK2+cdHOhkmltVzaBrNOZ/EGwyxkQWTSUKzLEJcrUoYm1Y/1UZYAACd7KlWxSf316kM17IHUPn013ingiCZzHIapwDiR5ggdTOjLWnfuulSXC4gabOSVq6izyndZdoRL6znlIwSIKaiccP5YIHKUxQpFYXqBCIvRDipWAEeRjsM98aQOoVfoWk8ETfnwOJEuTQQyLa8Qs5I4p9PP50OKv8HXv9Eda/Td2S3c2+KKUS3xc6OjZIi22vjJbpexKurB9eQEzfEMFDpO7UmXhsICE=
