version: '3.3'
services:
  post_db:
    image: mongo:${VERSION_MONGO}
    volumes:
      - post_db:/data/db
    networks:
      - back_net

  ui:
    image: ${USERNAME}/${IMG_UI}
    image: ${USERNAME}/${IMG_UI}:${VERSION}
    ports:
      - ${PORT}:${PORT}/tcp
    networks:
      - front_net

  post:
    image: ${USERNAME}/${IMG_POST}
    image: ${USERNAME}/${IMG_POST}:${VERSION}
    networks:
      - front_net
      - back_net

  comment:
    image: ${USERNAME}/${IMG_COM}
    image: ${USERNAME}/${IMG_COM}:${VERSION}
    networks:
      - front_net
      - back_net
    links:
      - "post_db:comment_db"

  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    networks:
      - front_net
      - back_net
    command:
    # Передаем доп. параметры в командной строке
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    # Задаем время хранения метрик в 1 день
      - '--storage.tsdb.retention=1d'

  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
      - front_net
      - back_net
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'

volumes:
  post_db:
  prometheus_data:

networks:
  front_net:
  back_net:
