version: '3.3'
services:
  post_db:
    image: mongo:${VERSION_MONGO}
    volumes:
      - post_db:/data/db
    networks:
      - back_net

  ui:
    image: ${USERNAME}/${IMG_UI}
    image: ${USERNAME}/${IMG_UI}:${VERSION}
    ports:
      - ${PORT}:${PORT}/tcp
    networks:
      - front_net

  post:
    image: ${USERNAME}/${IMG_POST}
    image: ${USERNAME}/${IMG_POST}:${VERSION}
    networks:
      - front_net
      - back_net

  comment:
    image: ${USERNAME}/${IMG_COM}
    image: ${USERNAME}/${IMG_COM}:${VERSION}
    networks:
      - front_net
      - back_net
    links:
      - "post_db:comment_db"

volumes:
  post_db:

networks:
  front_net:
  back_net:

