---
apiVersion: apps/v1
kind: Deployment
# Блок метаданных деплоя
metadata:
  name: post
  labels:
    app: reddit
    component: post
# Блок спецификации деплоя
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reddit
      component: post
# Блок описания pod-ов
  template:
    metadata:
      name: post
      labels:
        app: reddit
        component: post
    spec:
      containers:
      - image: yulka/post:1.0
        name: post
        env:
        - name: POST_DATABASE_HOST
          value: post-db

